/*
 * This file is generated by jOOQ.
 */
package com.ckdpharm.jooq.domain;


import com.ckdpharm.jooq.domain.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqtest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtest.author</code>.
     */
    public static final Author AUTHOR = com.ckdpharm.jooq.domain.tables.Author.AUTHOR;
}
